"""Declared OpenAPI operation coverage for the CLI.

Every operation in openapi.json must appear here as implemented or skipped.
When the bundled spec gains new ops, this map must be updated deliberately.
"""

# Status values: "implemented" | "skipped"
OPENAPI_COVERAGE: dict[str, str] = {
    "DELETE /api/v1/rdns/ipv4/{ip}": "implemented",
    "DELETE /api/v1/rdns/ipv6/{ip}": "implemented",
    "DELETE /api/v1/servers/{serverId}/interfaces/{mac}": "implemented",
    "DELETE /api/v1/servers/{serverId}/iso": "implemented",
    "DELETE /api/v1/servers/{serverId}/rescuesystem": "implemented",
    "DELETE /api/v1/servers/{serverId}/snapshots/{name}": "implemented",
    "DELETE /api/v1/users/{userId}/firewall-policies/{id}": "implemented",
    "DELETE /api/v1/users/{userId}/images/{key}": "implemented",
    "DELETE /api/v1/users/{userId}/isos/{key}": "implemented",
    "DELETE /api/v1/users/{userId}/ssh-keys/{id}": "implemented",
    "GET /api/ping": "implemented",
    "GET /api/v1/maintenance": "implemented",
    "GET /api/v1/openapi": "skipped",
    "GET /api/v1/rdns/ipv4/{ip}": "implemented",
    "GET /api/v1/rdns/ipv6/{ip}": "implemented",
    "GET /api/v1/servers": "implemented",
    "GET /api/v1/servers/{serverId}": "implemented",
    "GET /api/v1/servers/{serverId}/disks": "implemented",
    "GET /api/v1/servers/{serverId}/disks/supported-drivers": "implemented",
    "GET /api/v1/servers/{serverId}/disks/{diskName}": "implemented",
    "GET /api/v1/servers/{serverId}/gpu-driver": "implemented",
    "GET /api/v1/servers/{serverId}/guest-agent": "implemented",
    "GET /api/v1/servers/{serverId}/guest-agent/status": "implemented",
    "GET /api/v1/servers/{serverId}/imageflavours": "implemented",
    "GET /api/v1/servers/{serverId}/interfaces": "implemented",
    "GET /api/v1/servers/{serverId}/interfaces/{mac}": "implemented",
    "GET /api/v1/servers/{serverId}/interfaces/{mac}/firewall": "implemented",
    "GET /api/v1/servers/{serverId}/iso": "implemented",
    "GET /api/v1/servers/{serverId}/isoimages": "implemented",
    "GET /api/v1/servers/{serverId}/logs": "implemented",
    "GET /api/v1/servers/{serverId}/metrics/cpu": "implemented",
    "GET /api/v1/servers/{serverId}/metrics/disk": "implemented",
    "GET /api/v1/servers/{serverId}/metrics/network": "implemented",
    "GET /api/v1/servers/{serverId}/metrics/network/packet": "implemented",
    "GET /api/v1/servers/{serverId}/rescuesystem": "implemented",
    "GET /api/v1/servers/{serverId}/snapshots": "implemented",
    "GET /api/v1/servers/{serverId}/snapshots/{name}": "implemented",
    "GET /api/v1/tasks": "implemented",
    "GET /api/v1/tasks/{uuid}": "implemented",
    "GET /api/v1/users/{userId}": "implemented",
    "GET /api/v1/users/{userId}/failoverips/v4": "implemented",
    "GET /api/v1/users/{userId}/failoverips/v6": "implemented",
    "GET /api/v1/users/{userId}/firewall-policies": "implemented",
    "GET /api/v1/users/{userId}/firewall-policies/{id}": "implemented",
    "GET /api/v1/users/{userId}/images": "implemented",
    "GET /api/v1/users/{userId}/images/{key}": "implemented",
    "GET /api/v1/users/{userId}/images/{key}/{uploadId}/parts/{partNumber}": "implemented",
    "GET /api/v1/users/{userId}/isos": "implemented",
    "GET /api/v1/users/{userId}/isos/{key}": "implemented",
    "GET /api/v1/users/{userId}/isos/{key}/{uploadId}/parts/{partNumber}": "implemented",
    "GET /api/v1/users/{userId}/logs": "implemented",
    "GET /api/v1/users/{userId}/ssh-keys": "implemented",
    "GET /api/v1/users/{userId}/vlans": "implemented",
    "GET /api/v1/users/{userId}/vlans/{vlanId}": "implemented",
    "GET /api/v1/vlans/{vlanId}": "implemented",
    "PATCH /api/v1/servers/{serverId}": "implemented",
    "PATCH /api/v1/servers/{serverId}/disks": "implemented",
    "PATCH /api/v1/users/{userId}/failoverips/v4/{id}": "implemented",
    "PATCH /api/v1/users/{userId}/failoverips/v6/{id}": "implemented",
    "POST /api/v1/openapi/mcp": "skipped",
    "POST /api/v1/rdns/ipv4": "implemented",
    "POST /api/v1/rdns/ipv6": "implemented",
    "POST /api/v1/servers/{serverId}/disks/{diskName}:format": "implemented",
    "POST /api/v1/servers/{serverId}/image": "implemented",
    "POST /api/v1/servers/{serverId}/interfaces": "implemented",
    "POST /api/v1/servers/{serverId}/interfaces/{mac}/firewall:reapply": "implemented",
    (
        "POST /api/v1/servers/{serverId}/interfaces/{mac}/firewall:restore-copied-policies"
    ): "implemented",
    "POST /api/v1/servers/{serverId}/iso": "implemented",
    "POST /api/v1/servers/{serverId}/rescuesystem": "implemented",
    "POST /api/v1/servers/{serverId}/snapshots": "implemented",
    "POST /api/v1/servers/{serverId}/snapshots/{name}/export": "implemented",
    "POST /api/v1/servers/{serverId}/snapshots/{name}/revert": "implemented",
    "POST /api/v1/servers/{serverId}/snapshots:dryrun": "implemented",
    "POST /api/v1/servers/{serverId}/storageoptimization": "implemented",
    "POST /api/v1/servers/{serverId}/user-image": "implemented",
    "POST /api/v1/users/{userId}/firewall-policies": "implemented",
    "POST /api/v1/users/{userId}/images/{key}": "implemented",
    "POST /api/v1/users/{userId}/isos/{key}": "implemented",
    "POST /api/v1/users/{userId}/ssh-keys": "implemented",
    "PUT /api/v1/servers/{serverId}/interfaces/{mac}": "implemented",
    "PUT /api/v1/servers/{serverId}/interfaces/{mac}/firewall": "implemented",
    "PUT /api/v1/tasks/{uuid}:cancel": "implemented",
    "PUT /api/v1/users/{userId}": "implemented",
    "PUT /api/v1/users/{userId}/firewall-policies/{id}": "implemented",
    "PUT /api/v1/users/{userId}/images/{key}/{uploadId}": "implemented",
    "PUT /api/v1/users/{userId}/isos/{key}/{uploadId}": "implemented",
    "PUT /api/v1/users/{userId}/vlans/{vlanId}": "implemented",
}

SKIP_REASONS = {
    "GET /api/v1/openapi": "Spec fetch; CLI uses curl + bundled openapi.json",
    "POST /api/v1/openapi/mcp": "Explore-only MCP server; no CLI JSON-RPC wrapper",
}
